# Prometheus Configuration for OKD Cluster Monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'okd-dev'
    replica: 'prometheus-01'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'okd-dev-bootstrap:9100'
        - 'okd-dev-master-0:9100'
        - 'okd-dev-master-1:9100'
        - 'okd-dev-master-2:9100'
        - 'okd-dev-worker-0:9100'
        - 'okd-dev-worker-1:9100'
        - 'okd-dev-lb:9100'

  # OKD cluster metrics
  - job_name: 'okd-apiserver'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - default
            - kube-system
            - openshift-monitoring
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: kubernetes

  # Kubelet metrics
  - job_name: 'kubelet'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  # cAdvisor container metrics
  - job_name: 'cadvisor'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

  # HashiCorp Services
  - job_name: 'vault'
    static_configs:
      - targets: ['vault:8200']
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']

  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']

  # Security scanning services
  - job_name: 'trivy'
    static_configs:
      - targets: ['trivy:8080']

  # Load balancer metrics (HAProxy)
  - job_name: 'haproxy'
    static_configs:
      - targets: ['okd-dev-lb:8404']

  # VMware vSphere metrics (if vSphere exporter is deployed)
  - job_name: 'vsphere'
    static_configs:
      - targets: ['vsphere-exporter:9272']
    scrape_interval: 60s
    scrape_timeout: 30s